// Code generated by "stringer -type=Authn"; DO NOT EDIT.

package parser

import "strconv"

const (
	_Authn_name_0 = "AllowNoneAllowReadAllowInsert"
	_Authn_name_1 = "AllowUpdate"
	_Authn_name_2 = "AllowDelete"
	_Authn_name_3 = "AllowAll"
)

var (
	_Authn_index_0 = [...]uint8{0, 9, 18, 29}
)

func (i Authn) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _Authn_name_0[_Authn_index_0[i]:_Authn_index_0[i+1]]
	case i == 4:
		return _Authn_name_1
	case i == 8:
		return _Authn_name_2
	case i == 15:
		return _Authn_name_3
	default:
		return "Authn(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
