// Code generated by "stringer -type TokenType -trimprefix Token"; DO NOT EDIT.

package parser

import "strconv"

const _TokenType_name = "InvalidNewlineWSSymbolStringStringWithEscapeNumberIdentifierIdentifierQuotedLineCommentMultiComment"

var _TokenType_index = [...]uint8{0, 7, 14, 16, 22, 28, 44, 50, 60, 76, 87, 99}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
